<a href="https://colab.research.google.com/github/Adityazzzzz/Adityazzzzz/blob/main/ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Python**


In [ ]:
s = 'Programming'
print(s[1:9])

rogrammi


**Type of Objects in python**

Immuatable: int, float, sring, bool, tuple <br>
Mutatble: List, set, Dictionary

In [ ]:
#list can store any datatype

mylist = [1,2,3,4]
print(mylist)

myls2 = [1,'a',True]

# some basics functions
myls2.append('Bhopal')
print(len(myls2))
del myls2[1]
totallist = mylist + myls2

[1, 2, 3, 4]
[1, 'a', True, 'Bhopal']


In [ ]:
# tupple - ( )
# tupple can store different datatypes
# tupple are fixed.

t1 = (1,2,'a',True)

mylist1 = [1,2,3]
mytupple  = tuple(mylist1)

In [ ]:
# set - { }
# set are fixed

s1 = {1,2,3,4}

mylist1 = [1,2,3]
myset = set(mylist1)

In [ ]:
# loops

for i in range(5):
  print(input(i))


while i<10:
  print(i)

01
1
12
2
23
3
34
4
45
5


# NumPy

In [ ]:
# Allows several mathematical operations
# Faster to use working with arrays big and small
# supports N-dimensioal arrays
# [[1 2 3],[2 4 6],...]

import numpy as np

a = np.array([1,2,3])
b = np.array([(1,2,3),(1,2,3)])
print(b)
b.shape #tells the shape of arr

c = np.zeroes((2,2))    # creates 2x2 matrix with zeroes
d = np.ones((2,2))      # creates 2x2 matrix with ones
e = np.eye(2)           # creates 2x2 identity matrix
f = np.full((2,3),1)    # creates 2x3 matrix with all ele=1
g = np.random.random((2,2))  # creates 2x2 matrix with random values
h = np.random.randint(10,100,(2,3)) # creates 2x3 matrix with int values rane between 10-100

i = np.linspace(10,100,5) #returns 5 values b/w 10-100


#convert list to nparr
list1 = [1,2,3,4]
arr1 = np.asarray(list1)

In [10]:
arr=np.random.randint(1,10,(2,3))
print(arr)

arr.size  # operations on a arr
arr.shape

# mathematical operations
# element by element operation
a+b
a-b
a/b
a*b

t = np.transpose(arr)
arr2 = arr1.reshape(3,2)

[[6 4 5]
 [6 3 7]]


# Pandas
Used in data processing and analysis<br>

**Pandas Data Frame**: It is a 2-dimensional tabular data stucture with labelled axis
